import { createRequestHandler } from '@remix-run/vercel';

// @ts-ignore because the server build file is generated by `remix vite:build`
import * as serverBuild from '../build/server';

export default createRequestHandler({ build: serverBuild });
